In [1]:
import tensorflow as tf

/Users/mustafamuratarat/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [3]:
print(tf.__version__)

1.5.0


In [4]:
hello = tf.constant("Hello")

In [5]:
world = tf.constant("World")

In [6]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [7]:
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [10]:
with tf.Session() as sess:
    result = sess.run(hello+world)

In [11]:
print(result)

b'HelloWorld'


In [12]:
a=tf.constant(10)

In [13]:
b=tf.constant(20)

In [14]:
type(a)

tensorflow.python.framework.ops.Tensor

In [15]:
a+b

<tf.Tensor 'add_1:0' shape=() dtype=int32>

In [16]:
with tf.Session() as sess:
    result = sess.run(a+b)

In [17]:
result

30

In [31]:
const = tf.constant(10)

In [21]:
fill_mat = tf.fill((4,4),10)

In [22]:
myzeros = tf.zeros((4,4))

In [23]:
myones = tf.ones((4,4))

In [25]:
myrandn = tf.random_normal((4,4),mean=0,stddev=1.0)

In [26]:
myrandu = tf.random_uniform((4,4),minval=0,maxval=1)

In [32]:
myops = [const,fill_mat,myzeros,myones,myrandn,myrandu]

In [58]:
#Creating Interactive Session so we dont have to run 
#session everytime. Its only for Jupyter notebooks
sess = tf.InteractiveSession()

In [35]:
for op in myops:
    print(sess.run(op))
    print('\n')

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[ 0.5049567  -0.85292464 -0.88211626 -0.02244858]
 [-1.8381289   0.9380594  -0.06335025  0.5510455 ]
 [ 0.74290085 -0.07375596  1.0312024  -0.59892684]
 [-0.3296853  -1.9143119   0.5320827   0.02034567]]


[[0.5203763  0.9101888  0.04468024 0.32252145]
 [0.89625835 0.82988024 0.6738572  0.9160763 ]
 [0.08640742 0.2783928  0.02367795 0.87601554]
 [0.78468823 0.5760286  0.24912727 0.7035197 ]]




In [39]:
#or
sess = tf.InteractiveSession()
for op in myops:
    print(op.eval())
    print('\n')

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[ 0.86621517 -0.15789893 -0.0473299   1.4749527 ]
 [ 0.09352769  0.27726352  0.7545936  -1.3330778 ]
 [ 0.51289725  0.3484031   1.1862314   0.29699582]
 [-0.69791174  3.4144318  -0.5086536   1.6111802 ]]


[[0.8925308  0.15786397 0.29998958 0.71104527]
 [0.12390196 0.714965   0.37879932 0.91655445]
 [0.9758545  0.8493073  0.689911   0.04436862]
 [0.9595207  0.65802526 0.25814366 0.4643402 ]]




In [51]:
a = tf.constant([ [1,2], [3,4]])

In [52]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [53]:
b = tf.constant([[10],[100]])

In [54]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [55]:
result = tf.matmul(a,b)

In [56]:
sess.run(result)

array([[210],
       [430]], dtype=int32)

In [57]:
#Another way to see the result
result.eval()

array([[210],
       [430]], dtype=int32)