In [45]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
import tensorflow as tf
from math import sqrt
from sklearn.metrics import mean_squared_error
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
data = pd.read_csv('/Users/mustafamuratarat/Downloads/Tensorflow-Bootcamp-master/02-TensorFlow-Basics/cal_housing_clean.csv')

In [3]:
X = data.iloc[:,0:6] #data.drop(['medianHouseValue'],axis=1)
Y = data['medianHouseValue']

In [4]:
data.describe().transpose()

count           mean            std         min  \
housingMedianAge  20640.0      28.639486      12.585558      1.0000   
totalRooms        20640.0    2635.763081    2181.615252      2.0000   
totalBedrooms     20640.0     537.898014     421.247906      1.0000   
population        20640.0    1425.476744    1132.462122      3.0000   
households        20640.0     499.539680     382.329753      1.0000   
medianIncome      20640.0       3.870671       1.899822      0.4999   
medianHouseValue  20640.0  206855.816909  115395.615874  14999.0000   

                          25%          50%           75%          max  
housingMedianAge      18.0000      29.0000      37.00000      52.0000  
totalRooms          1447.7500    2127.0000    3148.00000   39320.0000  
totalBedrooms        295.0000     435.0000     647.00000    6445.0000  
population           787.0000    1166.0000    1725.00000   35682.0000  
households           280.0000     409.0000     605.00000    6082.0000  
medianIncome           2.5634       3.5348       4.74325      15.0001  
medianHouseValue  119600.0000  179700.0000  264725.00000  500001.0000

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3, random_state=101)

In [6]:
#Scale the data
#Use sklearn preprocessing to create a MinMaxScaler for the feature data. Fit this scaler only to the training data. 
#Then use it to transform X_test and X_train. Then use the scaled X_test and X_train along with pd.Dataframe to 
#re-create two dataframes of scaled data.
scaler = MinMaxScaler()
scaler.fit(X_train)
X_train = pd.DataFrame(data=scaler.transform(X_train),columns = X_train.columns,index=X_train.index)
X_test = pd.DataFrame(data=scaler.transform(X_test),columns = X_test.columns,index=X_test.index)

In [7]:
data.columns

Index(['housingMedianAge', 'totalRooms', 'totalBedrooms', 'population',
       'households', 'medianIncome', 'medianHouseValue'],
      dtype='object')

In [8]:
age = tf.feature_column.numeric_column('housingMedianAge')
rooms = tf.feature_column.numeric_column('totalRooms')
bedrooms = tf.feature_column.numeric_column('totalBedrooms')
population = tf.feature_column.numeric_column('population')
households = tf.feature_column.numeric_column('households')
income = tf.feature_column.numeric_column('medianIncome')

In [9]:
feat_columns=[age, rooms, bedrooms, population, households, income]

In [10]:
input_func = tf.estimator.inputs.pandas_input_fn(x=X_train, y=y_train, batch_size=10, num_epochs=1000,shuffle=True)

In [11]:
model = tf.estimator.DNNRegressor(hidden_units=[6,6,6],feature_columns=feat_columns)

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': '/var/folders/t9/wrvs828j3qx2tvhc10_c8b400000gn/T/tmptbh62zjy', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x1a1bbad518>, '_task_type': 'worker', '_task_id': 0, '_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}


In [22]:
model.train(input_fn=input_func, steps=25000)

INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Restoring parameters from /var/folders/t9/wrvs828j3qx2tvhc10_c8b400000gn/T/tmptbh62zjy/model.ckpt-1000
INFO:tensorflow:Saving checkpoints for 1001 into /var/folders/t9/wrvs828j3qx2tvhc10_c8b400000gn/T/tmptbh62zjy/model.ckpt.
INFO:tensorflow:loss = 245750370000.0, step = 1001
INFO:tensorflow:global_step/sec: 537.661
INFO:tensorflow:loss = 290478000000.0, step = 1101 (0.188 sec)
INFO:tensorflow:global_step/sec: 654.048
INFO:tensorflow:loss = 265748020000.0, step = 1201 (0.154 sec)
INFO:tensorflow:global_step/sec: 645.149
INFO:tensorflow:loss = 92418020000.0, step = 1301 (0.155 sec)
INFO:tensorflow:global_step/sec: 688.297
INFO:tensorflow:loss = 228073240000.0, step = 1401 (0.145 sec)
INFO:tensorflow:global_step/sec: 666.107
INFO:tensorflow:loss = 129306526000.0, step = 1501 (0.150 sec)
INFO:tensorflow:global_step/sec: 668.848
INFO:tensorflow:loss = 289140830000.0, step = 1601 (0.150 sec)
INFO:tensorflow:global_step/sec: 574.627


INFO:tensorflow:global_step/sec: 657.786
INFO:tensorflow:loss = 78360430000.0, step = 8701 (0.152 sec)
INFO:tensorflow:global_step/sec: 707.144
INFO:tensorflow:loss = 51508340000.0, step = 8801 (0.141 sec)
INFO:tensorflow:global_step/sec: 719.072
INFO:tensorflow:loss = 249588320000.0, step = 8901 (0.140 sec)
INFO:tensorflow:global_step/sec: 754.455
INFO:tensorflow:loss = 161171570000.0, step = 9001 (0.133 sec)
INFO:tensorflow:global_step/sec: 694.002
INFO:tensorflow:loss = 70875510000.0, step = 9101 (0.144 sec)
INFO:tensorflow:global_step/sec: 666.844
INFO:tensorflow:loss = 130380290000.0, step = 9201 (0.150 sec)
INFO:tensorflow:global_step/sec: 723.092
INFO:tensorflow:loss = 167310000000.0, step = 9301 (0.139 sec)
INFO:tensorflow:global_step/sec: 704.656
INFO:tensorflow:loss = 45097652000.0, step = 9401 (0.141 sec)
INFO:tensorflow:global_step/sec: 718.452
INFO:tensorflow:loss = 47405450000.0, step = 9501 (0.139 sec)
INFO:tensorflow:global_step/sec: 686.23
INFO:tensorflow:loss = 529427

INFO:tensorflow:global_step/sec: 597.968
INFO:tensorflow:loss = 126674800000.0, step = 16601 (0.167 sec)
INFO:tensorflow:global_step/sec: 635.724
INFO:tensorflow:loss = 66263024000.0, step = 16701 (0.159 sec)
INFO:tensorflow:global_step/sec: 607.577
INFO:tensorflow:loss = 65461027000.0, step = 16801 (0.163 sec)
INFO:tensorflow:global_step/sec: 661.084
INFO:tensorflow:loss = 42638220000.0, step = 16901 (0.151 sec)
INFO:tensorflow:global_step/sec: 697.092
INFO:tensorflow:loss = 89595360000.0, step = 17001 (0.144 sec)
INFO:tensorflow:global_step/sec: 676.298
INFO:tensorflow:loss = 108664490000.0, step = 17101 (0.148 sec)
INFO:tensorflow:global_step/sec: 590.365
INFO:tensorflow:loss = 116134020000.0, step = 17201 (0.169 sec)
INFO:tensorflow:global_step/sec: 641.177
INFO:tensorflow:loss = 53225505000.0, step = 17301 (0.157 sec)
INFO:tensorflow:global_step/sec: 652.733
INFO:tensorflow:loss = 41547543000.0, step = 17401 (0.153 sec)
INFO:tensorflow:global_step/sec: 679.344
INFO:tensorflow:loss

INFO:tensorflow:global_step/sec: 668.306
INFO:tensorflow:loss = 62344140000.0, step = 24501 (0.150 sec)
INFO:tensorflow:global_step/sec: 683.227
INFO:tensorflow:loss = 113709670000.0, step = 24601 (0.146 sec)
INFO:tensorflow:global_step/sec: 696.05
INFO:tensorflow:loss = 67603165000.0, step = 24701 (0.143 sec)
INFO:tensorflow:global_step/sec: 694.034
INFO:tensorflow:loss = 65395106000.0, step = 24801 (0.144 sec)
INFO:tensorflow:global_step/sec: 770.072
INFO:tensorflow:loss = 45200876000.0, step = 24901 (0.130 sec)
INFO:tensorflow:global_step/sec: 693.405
INFO:tensorflow:loss = 79280850000.0, step = 25001 (0.144 sec)
INFO:tensorflow:global_step/sec: 712.388
INFO:tensorflow:loss = 117177610000.0, step = 25101 (0.140 sec)
INFO:tensorflow:global_step/sec: 684.936
INFO:tensorflow:loss = 115881120000.0, step = 25201 (0.146 sec)
INFO:tensorflow:global_step/sec: 674.909
INFO:tensorflow:loss = 118315155000.0, step = 25301 (0.149 sec)
INFO:tensorflow:global_step/sec: 658.354
INFO:tensorflow:loss

In [23]:
eval_input_func = tf.estimator.inputs.pandas_input_fn(x=X_test, y=y_test, batch_size=10, num_epochs=1,shuffle=False)

In [24]:
predictions = model.predict(eval_input_func)

In [25]:
my_pred = list(predictions)

INFO:tensorflow:Restoring parameters from /var/folders/t9/wrvs828j3qx2tvhc10_c8b400000gn/T/tmptbh62zjy/model.ckpt-26000


In [26]:
my_pred

[{'predictions': array([241094.48], dtype=float32)},
 {'predictions': array([324072.12], dtype=float32)},
 {'predictions': array([212646.17], dtype=float32)},
 {'predictions': array([189633.05], dtype=float32)},
 {'predictions': array([289758.78], dtype=float32)},
 {'predictions': array([198803.14], dtype=float32)},
 {'predictions': array([225166.14], dtype=float32)},
 {'predictions': array([207035.05], dtype=float32)},
 {'predictions': array([223304.83], dtype=float32)},
 {'predictions': array([204144.7], dtype=float32)},
 {'predictions': array([205615.38], dtype=float32)},
 {'predictions': array([222471.52], dtype=float32)},
 {'predictions': array([193478.23], dtype=float32)},
 {'predictions': array([180222.05], dtype=float32)},
 {'predictions': array([262487.66], dtype=float32)},
 {'predictions': array([182123.36], dtype=float32)},
 {'predictions': array([200215.08], dtype=float32)},
 {'predictions': array([191229.92], dtype=float32)},
 {'predictions': array([184195.53], dtype=float

In [27]:
final_predictions =[]

for pred in my_pred:
    final_predictions.append(pred['predictions'])

In [28]:
final_predictions

[array([241094.48], dtype=float32),
 array([324072.12], dtype=float32),
 array([212646.17], dtype=float32),
 array([189633.05], dtype=float32),
 array([289758.78], dtype=float32),
 array([198803.14], dtype=float32),
 array([225166.14], dtype=float32),
 array([207035.05], dtype=float32),
 array([223304.83], dtype=float32),
 array([204144.7], dtype=float32),
 array([205615.38], dtype=float32),
 array([222471.52], dtype=float32),
 array([193478.23], dtype=float32),
 array([180222.05], dtype=float32),
 array([262487.66], dtype=float32),
 array([182123.36], dtype=float32),
 array([200215.08], dtype=float32),
 array([191229.92], dtype=float32),
 array([184195.53], dtype=float32),
 array([247016.03], dtype=float32),
 array([173967.39], dtype=float32),
 array([237353.7], dtype=float32),
 array([216797.8], dtype=float32),
 array([172032.02], dtype=float32),
 array([187448.39], dtype=float32),
 array([279010.88], dtype=float32),
 array([183466.17], dtype=float32),
 array([143892.27], dtype=float

In [46]:
sqrt(mean_squared_error(y_test, final_predictions))

#OR 
#from sklearn.metrics import mean_squared_error
#from math import sqrt

# sqrt(mean_squared_error(y_actual, y_predicted))

97535.43902870595

In [35]:
def rmse(predictions, targets):
    return np.sqrt(((predictions - targets) ** 2).mean())

In [40]:
rmse(np.asarray(y_test), np.asarray(final_predictions))

121504.64001347467

In [41]:
print(np.asarray(final_predictions))

[[241094.48]
 [324072.12]
 [212646.17]
 ...
 [147681.3 ]
 [177630.17]
 [237027.53]]


In [43]:
print(np.asarray(y_test))

[406200. 500001. 122900. ... 136300.  60800. 231000.]


In [50]:
y_true = [3, -0.5, 2, 7]
y_pred = [2.5, 0.0, 2, 8]

rmse(np.asarray(y_true), np.asarray(y_pred))

0.6123724356957945